# Generated by Django 3.1.4 on 2020-12-20 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=250)),
                ('PhoneNumber', models.CharField(max_length=25)),
                ('website_name', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('password', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mydb.topic')),
            ],
        ),
    ]
