# Generated by Django 3.1.4 on 2020-12-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0002_accessrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
    ]
