# Generated by Django 3.1.4 on 2020-12-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0003_auto_20201220_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.CharField(default='Comments', max_length=1500),
        ),
    ]
