# Generated by Django 3.1.4 on 2020-12-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0007_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='@+Pass', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
